# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0f7557b
_src_path: https://github.com/schwallergroup/copier-liac.git
author_email: octavian.susanu@epfl.ch
author_name: Octavian Susanu
enforce_code_style: true
github_org: octav19
package_name: cdk_package
project_name: CDK-Package
short_description: Helps visualize Smiles
